version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "CI/CD"
      - "dependency"
      - "bot"
    target-branch: "master"

  # Maintain dependencies for Pip
  - package-ecosystem: "pip"
    directory: "config/"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependency"
      - "bot"
    target-branch: "master"
  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"  
    labels:
      - "docker"
      - "dependency"
      - "bot"
