version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
      - "bot"
    target-branch: "master"

  # Maintain dependencies for Pip
  - package-ecosystem: "pip"
    directory: "config/"
    schedule:
      interval: "monthly"
    labels:
      - "dependency"
      - "bot"
    target-branch: "master"
    
