site_name: !ENV REPOSITORY
site_url: ""
use_directory_urls: false
docs_dir: !ENV SRC
theme:
  name: gitbook
plugins:
  - search
  - minify: # Minifies HTML
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
  # - drawio-exporter: # Allows embeddding .drawio files
  #       # Diagrams are cached to speed up site generation. The default path is
  #       # drawio-exporter, relative to the documentation directory.
  #       cache_dir: 'drawio-exporter'
  #       format: svg
  #       embed_format: '{img_open}{img_src}{img_close}'
  #       sources: '*.drawio'
  - git-revision-date-localized:
      type: datetime
      timezone: UTC
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true
  # - git-authors: # You can use {{ git_page_authors }} {{ git_site_authors }} inside markdown files
  #     show_contribution: true
  #     show_line_count: true
  #     count_empty_lines: false


  - print-site: # Must be the last one
      add_to_navigation: true
      print_page_title: 'PDF'
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Index'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      path_to_pdf: ""
