name: Update documentation




jobs:
  update-gh-pages:
    if: startsWith(github.ref, 'refs/tags/v')
      name: Generate and upload new GitHub Pages
      runs-on: ubuntu-latest
      needs:
        - push-to-registries
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Run action
          uses: ./
          with:
            src: .
            dst: ./result
        - name: Deploy GH Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./result
