name: Update documentation

on:
  push:
    branches:
      - master
    paths: 
      - "*.md"
      - "**/*.md"

jobs:
  update-gh-pages:
    name: Generate and upload new GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run action
        uses: ./
        with:
          src: .
          dst: ./result
          icon: file-document-edit
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
