name: Call self to test
on:
  push:
    branches:
      - "master"
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Test mode HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: ./
        with:
          mode: HTML
          src: .
          dst: ./result
          